import type { ArmourBuild } from "./armourValues";
import type { HitLocationCode, MountPoint } from "./hitLocations";

export type GarmentSlotType =
  "Clothing" | "Padding" | "Flexible" | "Rigid" | "Outer";

// "shared" = one item, one equip action, covers both sides of its Mount
// (a Hauberk is one continuous garment). "left"/"right" = an individually
// worn piece that covers only that side -- equipping both sides means
// equipping two separate catalog entries. See the file header note for the
// classification rule.
export type Laterality = "shared" | "left" | "right";

export interface CatalogItem {
  id: string;
  name: string;
  build: ArmourBuild;
  garmentSlots: readonly GarmentSlotType[];
  mount: MountPoint;
  // A garment spanning two Mounts (e.g. Trousers, belted at Hp but reaching
  // down to Tg) also competes for a slot at each of these. Omitted for every
  // single-Mount item -- most of the catalog. See file header note.
  additionalMounts?: readonly MountPoint[];
  cover: readonly HitLocationCode[];
  gapPercent: number;
  enc: number;
  costSp: number;
  laterality: Laterality;
}

// Transcribed from the design doc's per-Build item tables (Cloth, Quilted,
// Leather, Mail, Splint, Scale, Lamellar, Plate, Articulated Plate). Hide,
// Coat of Plates, Brigandine, and Coat are excluded -- see armourValues.ts.
//
// Two items (Tunic, Mail Hauberk) have their Cover list taken from the doc's
// "Working Examples" section rather than their own per-Build table: both
// per-Build rows omit Hp, but the worked examples' own totals only add up
// (matching the published B/S/P/F/M/C numbers at the Hip row) if Hp is
// included. Flagged inline below.
//
// Every "Chausses" item (Cloth, Quilted, Leather, Mail, Scale, Lamellar)
// mounts at Tg, matching where its Cover actually starts (the design doc's
// own Cover list still lists Hp for Chausses as of this writing; this
// catalog excludes it -- the armour only protects from the thigh down, and
// this catalog has been corrected ahead of that doc update).
//
// A hip-only drape (Kilt, Braies, and every build's "Skirt" item -- Cover
// tops out at Tg, never reaching Kn) mounts at Hp alone, so it no longer
// conflicts with Chausses: a mail skirt hanging from the waist and separate
// mail chausses on the legs is a normal combo, not a redundant one, and
// blocking it was a bug (both were mounted at Hp, purely because Chausses
// used to be too). This also stops a Splint/Plate Fauld from being falsely
// blocked by a Scale/Lamellar Chausses that never actually overlapped it in
// Cover.
//
// A genuine full-leg garment (Trousers, Hose, Arming Hose, Leather Leggings)
// -- Cover reaches Kn/Cf, same span as Chausses -- is belted at Hp *and*
// reaches down through Tg, so it needs additionalMounts: ["Tg"] to still
// compete with Chausses for the Tg slot: these are two different styles of
// the same full-leg coverage, and wearing both is redundant, correctly
// blocked. Scale Leggings and Lamellar Leggings don't need this: they're
// already mounted at Tg alone (not Hp), which already matches Chausses'
// Tg mount directly with no additionalMounts required.
//
// Scale keeps "Flexible + Rigid": its own build description says the scales
// are "attached to a flexible backing," so the backing is part of the piece
// and already does a Mail-equivalent layer's job -- no separate Flexible
// item fits underneath. Lamellar is "Rigid" only, despite looking like the
// same construction: its own description says lamellae are "laced plates
// requiring no cloth backing" -- the plates lace directly to each other for
// structure, with no separate flexible garment involved, so unlike Scale it
// does not block a Mail layer worn underneath.
//
// gapPercent provenance: most values are still the design doc's own
// hand-picked numbers. A few (flagged inline where changed) were instead
// cross-checked against a separate published "Coverage %" table (per-piece
// body-region coverage, not itself a Gap figure). That table's Coverage% is
// read as (raw d100 width of the piece's covered locations) x (how
// completely it fills them) -- so dividing a piece's Coverage% by the sum of
// its own covered locations' rangeEnd-rangeStart+1 widths in HIT_LOCATIONS
// backs out local completeness, and 100% minus that is the Gap. Only applied
// where the source table's location list maps onto ours without ambiguity;
// left untouched anywhere the source's own abbreviations don't resolve
// cleanly (e.g. whether an unqualified "Ua" on a draped garment means
// upper-arm-only or shorthand for the whole arm below the shoulder changes
// the answer for several Mail pieces enough that guessing wasn't justified).
//
// Face coverage: gapPercent is purely informational (the Strike Gap Exploit
// stat) -- resolveHitLocationTable sums a covering item's full armour values
// at every location it covers regardless of gapPercent, so a high gap on an
// included location still grants full protection there. That means "this
// piece barely guards the face" has to be expressed by leaving Fa out of
// cover entirely, not by raising gapPercent. Plain coifs/hoods (Cloth,
// Quilted, Leather, Mail, Lamellar) don't cover Fa -- they frame the face,
// leaving eyes/nose/mouth open, same as history: faces stayed vulnerable
// outside of an actual visored helm. Scale Coif is the one exception (kept,
// flagged inline) since its plates extend over the cheeks/jaw, unlike an
// open mail weave. Great helms, close helms, armets, bevors, and similar
// full/partial-face Plate pieces are unaffected -- they already have a real
// enclosing or jaw-guarding structure behind their Fa coverage.
//
// Laterality: an item mounted at Sh/Ua/El/Fo (arm points) or Ha/Ft
// (hands/feet) is worn individually per side -- two separate catalog
// entries, "(Right)" and "(Left)" -- regardless of build, since a single
// pauldron/vambrace/gauntlet/boot only ever covers one limb. Everything
// else (central mounts -- Sk, Fa, Nk, Th, Ab, Gr, Hp, and the Tg/Kn/Cf leg
// mounts used only by full torso-to-leg garments) stays "shared": one item,
// one equip action, both sides. Articulated Plate is a full explicit
// exception -- every piece there (including the Harnesses, which do cover
// arms/hands/legs/feet as part of one complete integrated suit) stays
// "shared", since it's sold and worn as one complete kit rather than
// individually-fitted components. Split items' ENC/Cost are half their
// original (undivided) values.
export const CATALOG: readonly CatalogItem[] = [
  // --- Cloth (Clothing) ---
  {
    id: "headband",
    name: "Headband",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Fa",
    cover: ["Fa"],
    gapPercent: 0,
    enc: 0.1,
    costSp: 2,
    laterality: "shared",
  },
  {
    id: "cap",
    name: "Cap",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Sk",
    cover: ["Sk"],
    gapPercent: 0,
    enc: 0.2,
    costSp: 5,
    laterality: "shared",
  },
  {
    // Doesn't cover Fa -- a coif frames the face, it doesn't guard it. See
    // file header note on Face coverage.
    id: "coif",
    name: "Coif",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Sk",
    cover: ["Sk"],
    gapPercent: 5,
    enc: 0.4,
    costSp: 8,
    laterality: "shared",
  },
  {
    // Doesn't cover Fa -- see file header note on Face coverage.
    id: "hood",
    name: "Hood",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Sk",
    cover: ["Sk", "Nk"],
    gapPercent: 5,
    enc: 0.6,
    costSp: 12,
    laterality: "shared",
  },
  {
    id: "shirt",
    name: "Shirt",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Th",
    cover: ["Th", "Ab", "RSh", "LSh", "RUA", "LUA"],
    gapPercent: 0,
    enc: 0.8,
    costSp: 15,
    laterality: "shared",
  },
  {
    id: "vest",
    name: "Vest",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Th",
    cover: ["Th", "Ab"],
    gapPercent: 0,
    enc: 0.5,
    costSp: 16,
    laterality: "shared",
  },
  {
    // Cover per the "Working Examples" section (includes Hp); the Cloth
    // table's own Tunic row omits it. See file header note.
    id: "tunic",
    name: "Tunic",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Th",
    cover: ["Th", "Ab", "Gr", "Hp", "RSh", "LSh", "RUA", "LUA"],
    gapPercent: 0,
    enc: 1.2,
    costSp: 22,
    laterality: "shared",
  },
  {
    id: "sleeves-right",
    name: "Sleeves (Right)",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Sh",
    cover: ["RSh", "RUA", "REl", "RFo"],
    gapPercent: 0,
    enc: 0.25,
    costSp: 5,
    laterality: "right",
  },
  {
    id: "sleeves-left",
    name: "Sleeves (Left)",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Sh",
    cover: ["LSh", "LUA", "LEl", "LFo"],
    gapPercent: 0,
    enc: 0.25,
    costSp: 5,
    laterality: "left",
  },
  {
    id: "gloves-right",
    name: "Gloves (Right)",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Ha",
    cover: ["RHa"],
    gapPercent: 5,
    enc: 0.1,
    costSp: 5,
    laterality: "right",
  },
  {
    id: "gloves-left",
    name: "Gloves (Left)",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Ha",
    cover: ["LHa"],
    gapPercent: 5,
    enc: 0.1,
    costSp: 5,
    laterality: "left",
  },
  {
    id: "loincloth",
    name: "Loincloth",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Gr",
    cover: ["Gr"],
    gapPercent: 20,
    enc: 0.1,
    costSp: 5,
    laterality: "shared",
  },
  {
    id: "braies",
    name: "Braies",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Hp",
    cover: ["Gr", "Hp", "RTg", "LTg"],
    gapPercent: 5,
    enc: 0.5,
    costSp: 12,
    laterality: "shared",
  },
  {
    id: "kilt",
    name: "Kilt",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Hp",
    cover: ["Hp", "Gr", "RTg", "LTg"],
    gapPercent: 10,
    enc: 0.7,
    costSp: 18,
    laterality: "shared",
  },
  {
    id: "trousers",
    name: "Trousers",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Hp",
    additionalMounts: ["Tg"],
    cover: ["Hp", "Gr", "RTg", "LTg", "RKn", "LKn", "RCf", "LCf"],
    gapPercent: 0,
    enc: 1.1,
    costSp: 22,
    laterality: "shared",
  },
  {
    id: "hose",
    name: "Hose",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Hp",
    additionalMounts: ["Tg"],
    cover: ["Hp", "RTg", "LTg", "RKn", "LKn", "RCf", "LCf", "RFt", "LFt"],
    gapPercent: 5,
    enc: 1.2,
    costSp: 20,
    laterality: "shared",
  },
  {
    id: "chausses-cloth",
    name: "Chausses (Cloth)",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Tg",
    cover: ["RTg", "LTg", "RKn", "LKn", "RCf", "LCf", "RFt", "LFt"],
    gapPercent: 5,
    enc: 1.4,
    costSp: 25,
    laterality: "shared",
  },
  {
    id: "socks-right",
    name: "Socks (Right)",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Ft",
    cover: ["RFt"],
    gapPercent: 0,
    enc: 0.05,
    costSp: 2.5,
    laterality: "right",
  },
  {
    id: "socks-left",
    name: "Socks (Left)",
    build: "Cloth",
    garmentSlots: ["Clothing"],
    mount: "Ft",
    cover: ["LFt"],
    gapPercent: 0,
    enc: 0.05,
    costSp: 2.5,
    laterality: "left",
  },

  // --- Quilted (Padding) ---
  {
    id: "arming-cap",
    name: "Arming Cap",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Sk",
    cover: ["Sk"],
    gapPercent: 0,
    enc: 0.2,
    costSp: 12,
    laterality: "shared",
  },
  {
    // Doesn't cover Fa -- see file header note on Face coverage.
    id: "padded-coif",
    name: "Padded Coif",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Sk",
    cover: ["Sk", "Nk"],
    gapPercent: 5,
    enc: 0.5,
    costSp: 18,
    laterality: "shared",
  },
  {
    id: "arming-collar",
    name: "Arming Collar",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Nk",
    cover: ["Nk"],
    gapPercent: 0,
    enc: 0.2,
    costSp: 10,
    laterality: "shared",
  },
  {
    id: "gambeson-vest",
    name: "Gambeson Vest",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Th",
    cover: ["Th", "Ab"],
    gapPercent: 0,
    enc: 1.0,
    costSp: 45,
    laterality: "shared",
  },
  {
    id: "gambeson",
    name: "Gambeson",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Th",
    cover: ["Th", "Ab", "RSh", "LSh", "RUA", "LUA"],
    gapPercent: 0,
    enc: 1.8,
    costSp: 80,
    laterality: "shared",
  },
  {
    id: "arming-doublet",
    name: "Arming Doublet",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Th",
    cover: ["Th", "Ab", "RSh", "LSh", "RUA", "LUA", "REl", "LEl", "RFo", "LFo"],
    gapPercent: 5,
    enc: 2.2,
    costSp: 90,
    laterality: "shared",
  },
  {
    id: "aketon",
    name: "Aketon",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Th",
    cover: [
      "Th",
      "Ab",
      "Gr",
      "Hp",
      "RTg",
      "LTg",
      "RSh",
      "LSh",
      "RUA",
      "LUA",
      "REl",
      "LEl",
      "RFo",
      "LFo",
    ],
    gapPercent: 5,
    enc: 2.8,
    costSp: 110,
    laterality: "shared",
  },
  {
    id: "padded-sleeves-right",
    name: "Padded Sleeves (Right)",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Sh",
    cover: ["RSh", "RUA", "REl", "RFo"],
    gapPercent: 5,
    enc: 0.4,
    costSp: 17.5,
    laterality: "right",
  },
  {
    id: "padded-sleeves-left",
    name: "Padded Sleeves (Left)",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Sh",
    cover: ["LSh", "LUA", "LEl", "LFo"],
    gapPercent: 5,
    enc: 0.4,
    costSp: 17.5,
    laterality: "left",
  },
  {
    id: "padded-gloves-right",
    name: "Padded Gloves (Right)",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Ha",
    cover: ["RHa"],
    gapPercent: 10,
    enc: 0.15,
    costSp: 10,
    laterality: "right",
  },
  {
    id: "padded-gloves-left",
    name: "Padded Gloves (Left)",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Ha",
    cover: ["LHa"],
    gapPercent: 10,
    enc: 0.15,
    costSp: 10,
    laterality: "left",
  },
  {
    id: "arming-hose",
    name: "Arming Hose",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Hp",
    additionalMounts: ["Tg"],
    cover: ["Hp", "Gr", "RTg", "LTg", "RKn", "LKn", "RCf", "LCf"],
    gapPercent: 5,
    enc: 1.4,
    costSp: 40,
    laterality: "shared",
  },
  {
    id: "padded-chausses",
    name: "Padded Chausses",
    build: "Quilted",
    garmentSlots: ["Padding"],
    mount: "Tg",
    cover: ["RTg", "LTg", "RKn", "LKn", "RCf", "LCf", "RFt", "LFt"],
    gapPercent: 5,
    enc: 1.8,
    costSp: 75,
    laterality: "shared",
  },

  // --- Leather (Padding) ---
  {
    id: "leather-cap",
    name: "Leather Cap",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Sk",
    cover: ["Sk"],
    gapPercent: 10,
    enc: 0.2,
    costSp: 15,
    laterality: "shared",
  },
  {
    // Doesn't cover Fa -- see file header note on Face coverage.
    id: "leather-coif",
    name: "Leather Coif",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Sk",
    cover: ["Sk", "Nk"],
    gapPercent: 10,
    enc: 0.5,
    costSp: 25,
    laterality: "shared",
  },
  {
    id: "leather-gorget",
    name: "Leather Gorget",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Nk",
    cover: ["Nk"],
    gapPercent: 10,
    enc: 0.3,
    costSp: 18,
    laterality: "shared",
  },
  {
    id: "leather-vest",
    name: "Leather Vest",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Th",
    cover: ["Th", "Ab"],
    gapPercent: 0,
    enc: 0.8,
    costSp: 60,
    laterality: "shared",
  },
  {
    id: "leather-jerkin",
    name: "Leather Jerkin",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Th",
    cover: ["Th", "Ab", "RSh", "LSh", "RUA", "LUA"],
    gapPercent: 10,
    enc: 1.5,
    costSp: 110,
    laterality: "shared",
  },
  {
    id: "leather-coat",
    name: "Leather Coat",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Th",
    cover: [
      "Th",
      "Ab",
      "Gr",
      "Hp",
      "RTg",
      "LTg",
      "RSh",
      "LSh",
      "RUA",
      "LUA",
      "REl",
      "LEl",
      "RFo",
      "LFo",
    ],
    gapPercent: 15,
    enc: 2.2,
    costSp: 170,
    laterality: "shared",
  },
  {
    id: "leather-sleeves-right",
    name: "Leather Sleeves (Right)",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Sh",
    cover: ["RSh", "RUA", "REl", "RFo"],
    gapPercent: 20,
    enc: 0.3,
    costSp: 22.5,
    laterality: "right",
  },
  {
    id: "leather-sleeves-left",
    name: "Leather Sleeves (Left)",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Sh",
    cover: ["LSh", "LUA", "LEl", "LFo"],
    gapPercent: 20,
    enc: 0.3,
    costSp: 22.5,
    laterality: "left",
  },
  {
    id: "leather-gloves-right",
    name: "Leather Gloves (Right)",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Ha",
    cover: ["RHa"],
    gapPercent: 30,
    enc: 0.15,
    costSp: 12.5,
    laterality: "right",
  },
  {
    id: "leather-gloves-left",
    name: "Leather Gloves (Left)",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Ha",
    cover: ["LHa"],
    gapPercent: 30,
    enc: 0.15,
    costSp: 12.5,
    laterality: "left",
  },
  {
    id: "leather-skirt",
    name: "Leather Skirt",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Hp",
    cover: ["Hp", "Gr", "RTg", "LTg"],
    gapPercent: 10,
    enc: 0.6,
    costSp: 40,
    laterality: "shared",
  },
  {
    id: "leather-leggings",
    name: "Leather Leggings",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Hp",
    additionalMounts: ["Tg"],
    cover: ["Hp", "RTg", "LTg", "RKn", "LKn", "RCf", "LCf"],
    gapPercent: 20,
    enc: 1.4,
    costSp: 100,
    laterality: "shared",
  },
  {
    id: "leather-chausses",
    name: "Leather Chausses",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Tg",
    cover: ["RTg", "LTg", "RKn", "LKn", "RCf", "LCf", "RFt", "LFt"],
    gapPercent: 15,
    enc: 1.7,
    costSp: 120,
    laterality: "shared",
  },
  {
    id: "leather-shoes-right",
    name: "Leather Shoes (Right)",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Ft",
    cover: ["RFt"],
    gapPercent: 10,
    enc: 0.2,
    costSp: 17.5,
    laterality: "right",
  },
  {
    id: "leather-shoes-left",
    name: "Leather Shoes (Left)",
    build: "Leather",
    garmentSlots: ["Padding"],
    mount: "Ft",
    cover: ["LFt"],
    gapPercent: 10,
    enc: 0.2,
    costSp: 17.5,
    laterality: "left",
  },

  // --- Mail (Flexible) ---
  {
    id: "mail-standard",
    name: "Mail Standard",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Nk",
    cover: ["Nk"],
    gapPercent: 0,
    enc: 0.3,
    costSp: 100,
    laterality: "shared",
  },
  {
    // Doesn't cover Fa -- a mail coif is an open oval around the face, not a
    // guard over it. See file header note on Face coverage.
    id: "mail-coif",
    name: "Mail Coif",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Sk",
    cover: ["Sk", "Nk"],
    gapPercent: 5,
    enc: 0.7,
    costSp: 220,
    laterality: "shared",
  },
  {
    id: "mail-mantle",
    name: "Mail Mantle",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Nk",
    cover: ["Nk", "RSh", "LSh", "Th"],
    gapPercent: 5,
    enc: 0.8,
    costSp: 250,
    laterality: "shared",
  },
  {
    id: "mail-vest",
    name: "Mail Vest",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Th",
    cover: ["Th", "Ab"],
    gapPercent: 0,
    enc: 2.2,
    costSp: 600,
    laterality: "shared",
  },
  {
    // Cover per the "Working Examples" section (includes Hp); the Mail
    // table's own Mail Hauberk row omits it. See file header note.
    // Cross-checked against a published Coverage-table: a full-length mail
    // hauberk's Coverage% comes out at or above its raw d100 budget for the
    // torso+arms it covers either way "Ua" is read (upper-arm-only with an
    // implicit Gr/Hp extension, or shorthand for the whole arm below the
    // shoulder) -- i.e. ~0% local gap either way. The existing 5% here is
    // already a reasonable (slightly conservative) match; not changed.
    id: "mail-hauberk",
    name: "Mail Hauberk",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Th",
    cover: [
      "Th",
      "Ab",
      "Gr",
      "Hp",
      "RSh",
      "LSh",
      "RUA",
      "LUA",
      "REl",
      "LEl",
      "RFo",
      "LFo",
    ],
    gapPercent: 5,
    enc: 3.8,
    costSp: 1400,
    laterality: "shared",
  },
  {
    id: "mail-byrnie",
    name: "Mail Byrnie",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Th",
    cover: ["Th", "Ab", "RSh", "LSh", "RUA", "LUA"],
    gapPercent: 5,
    enc: 3.2,
    costSp: 1200,
    laterality: "shared",
  },
  {
    id: "mail-voiders-right",
    name: "Mail Voiders (Right)",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Sh",
    cover: ["RSh", "RUA", "REl", "RFo"],
    gapPercent: 10,
    enc: 0.5,
    costSp: 175,
    laterality: "right",
  },
  {
    id: "mail-voiders-left",
    name: "Mail Voiders (Left)",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Sh",
    cover: ["LSh", "LUA", "LEl", "LFo"],
    gapPercent: 10,
    enc: 0.5,
    costSp: 175,
    laterality: "left",
  },
  {
    // Gap derived from a published Coverage-table cross-check: a mailed hand
    // covers ~5% of the whole d100 chart against a ~6% raw Ha budget (RHa+LHa
    // combined), i.e. ~83% locally complete -> ~15% gap. See file header note.
    id: "mail-mittens-right",
    name: "Mail Mittens (Right)",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Ha",
    cover: ["RHa"],
    gapPercent: 15,
    enc: 0.25,
    costSp: 110,
    laterality: "right",
  },
  {
    id: "mail-mittens-left",
    name: "Mail Mittens (Left)",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Ha",
    cover: ["LHa"],
    gapPercent: 15,
    enc: 0.25,
    costSp: 110,
    laterality: "left",
  },
  {
    id: "mail-skirt",
    name: "Mail Skirt",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Hp",
    cover: ["Hp", "Gr", "RTg", "LTg"],
    gapPercent: 5,
    enc: 1.2,
    costSp: 400,
    laterality: "shared",
  },
  {
    // Gap 15, matching the design doc's own hand-picked value -- this had
    // silently drifted to 5 (a plain transcription slip, never an
    // intentional pilot change like Mittens' below). The inner thigh isn't
    // actually protected by mail chausses, unlike a full hauberk's torso
    // coverage, so it doesn't get the Hauberk's ~0% treatment.
    id: "mail-chausses",
    name: "Mail Chausses",
    build: "Mail",
    garmentSlots: ["Flexible"],
    mount: "Tg",
    cover: ["RTg", "LTg", "RKn", "LKn", "RCf", "LCf", "RFt", "LFt"],
    gapPercent: 15,
    enc: 2.8,
    costSp: 1000,
    laterality: "shared",
  },

  // --- Splint (Rigid) -- every lateral piece here is individually forged ---
  {
    id: "splint-gorget",
    name: "Splint Gorget",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Nk",
    cover: ["Nk"],
    gapPercent: 10,
    enc: 0.4,
    costSp: 55,
    laterality: "shared",
  },
  {
    id: "splint-spaulders-right",
    name: "Splint Spaulders (Right)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Sh",
    cover: ["RSh"],
    gapPercent: 20,
    enc: 0.4,
    costSp: 65,
    laterality: "right",
  },
  {
    id: "splint-spaulders-left",
    name: "Splint Spaulders (Left)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Sh",
    cover: ["LSh"],
    gapPercent: 20,
    enc: 0.4,
    costSp: 65,
    laterality: "left",
  },
  {
    id: "splint-rerebraces-right",
    name: "Splint Rerebraces (Right)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Ua",
    cover: ["RUA"],
    gapPercent: 15,
    enc: 0.45,
    costSp: 80,
    laterality: "right",
  },
  {
    id: "splint-rerebraces-left",
    name: "Splint Rerebraces (Left)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Ua",
    cover: ["LUA"],
    gapPercent: 15,
    enc: 0.45,
    costSp: 80,
    laterality: "left",
  },
  {
    id: "splint-couters-right",
    name: "Splint Couters (Right)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "El",
    cover: ["REl"],
    gapPercent: 30,
    enc: 0.2,
    costSp: 40,
    laterality: "right",
  },
  {
    id: "splint-couters-left",
    name: "Splint Couters (Left)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "El",
    cover: ["LEl"],
    gapPercent: 30,
    enc: 0.2,
    costSp: 40,
    laterality: "left",
  },
  {
    id: "splint-vambraces-right",
    name: "Splint Vambraces (Right)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Fo",
    cover: ["RFo"],
    gapPercent: 15,
    enc: 0.4,
    costSp: 75,
    laterality: "right",
  },
  {
    id: "splint-vambraces-left",
    name: "Splint Vambraces (Left)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Fo",
    cover: ["LFo"],
    gapPercent: 15,
    enc: 0.4,
    costSp: 75,
    laterality: "left",
  },
  {
    id: "splint-gauntlets-right",
    name: "Splint Gauntlets (Right)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Ha",
    cover: ["RHa"],
    gapPercent: 25,
    enc: 0.35,
    costSp: 90,
    laterality: "right",
  },
  {
    id: "splint-gauntlets-left",
    name: "Splint Gauntlets (Left)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Ha",
    cover: ["LHa"],
    gapPercent: 25,
    enc: 0.35,
    costSp: 90,
    laterality: "left",
  },
  {
    id: "splint-cuirass",
    name: "Splint Cuirass",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Th",
    cover: ["Th", "Ab"],
    gapPercent: 5,
    enc: 3.2,
    costSp: 600,
    laterality: "shared",
  },
  {
    id: "splint-fauld",
    name: "Splint Fauld",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Hp",
    cover: ["Hp", "Gr"],
    gapPercent: 15,
    enc: 1.0,
    costSp: 170,
    laterality: "shared",
  },
  {
    id: "splint-cuisses-right",
    name: "Splint Cuisses (Right)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Tg",
    cover: ["RTg"],
    gapPercent: 20,
    enc: 0.6,
    costSp: 110,
    laterality: "right",
  },
  {
    id: "splint-cuisses-left",
    name: "Splint Cuisses (Left)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Tg",
    cover: ["LTg"],
    gapPercent: 20,
    enc: 0.6,
    costSp: 110,
    laterality: "left",
  },
  {
    id: "splint-poleyns-right",
    name: "Splint Poleyns (Right)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Kn",
    cover: ["RKn"],
    gapPercent: 30,
    enc: 0.25,
    costSp: 50,
    laterality: "right",
  },
  {
    id: "splint-poleyns-left",
    name: "Splint Poleyns (Left)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Kn",
    cover: ["LKn"],
    gapPercent: 30,
    enc: 0.25,
    costSp: 50,
    laterality: "left",
  },
  {
    id: "splint-greaves-right",
    name: "Splint Greaves (Right)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Cf",
    cover: ["RCf"],
    gapPercent: 15,
    enc: 0.5,
    costSp: 95,
    laterality: "right",
  },
  {
    id: "splint-greaves-left",
    name: "Splint Greaves (Left)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Cf",
    cover: ["LCf"],
    gapPercent: 15,
    enc: 0.5,
    costSp: 95,
    laterality: "left",
  },
  {
    id: "splint-sabatons-right",
    name: "Splint Sabatons (Right)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Ft",
    cover: ["RFt"],
    gapPercent: 25,
    enc: 0.4,
    costSp: 80,
    laterality: "right",
  },
  {
    id: "splint-sabatons-left",
    name: "Splint Sabatons (Left)",
    build: "Splint",
    garmentSlots: ["Rigid"],
    mount: "Ft",
    cover: ["LFt"],
    gapPercent: 25,
    enc: 0.4,
    costSp: 80,
    laterality: "left",
  },

  // --- Scale (Flexible + Rigid) ---
  {
    id: "scale-collar",
    name: "Scale Collar",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Nk",
    cover: ["Nk"],
    gapPercent: 10,
    enc: 0.4,
    costSp: 55,
    laterality: "shared",
  },
  {
    // Keeps Fa, unlike the other Coifs -- a scale hood's plates extend down
    // over the cheeks/jaw, unlike a mail coif's open weave. Still only a
    // partial guard (the center of the face is open), but our model can't
    // express partial coverage of a single Hit Location, so this is the
    // closer of the two binary options. See file header note.
    id: "scale-coif",
    name: "Scale Coif",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Sk",
    cover: ["Sk", "Fa", "Nk"],
    gapPercent: 15,
    enc: 0.8,
    costSp: 110,
    laterality: "shared",
  },
  {
    id: "scale-mantlet",
    name: "Scale Mantlet",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Nk",
    cover: ["Nk", "RSh", "LSh", "Th"],
    gapPercent: 10,
    enc: 1.0,
    costSp: 130,
    laterality: "shared",
  },
  {
    id: "scale-vest",
    name: "Scale Vest",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Th",
    cover: ["Th", "Ab"],
    gapPercent: 5,
    enc: 2.4,
    costSp: 300,
    laterality: "shared",
  },
  {
    id: "scale-cuirass",
    name: "Scale Cuirass",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Th",
    cover: ["Th", "Ab", "RSh", "LSh", "RUA", "LUA"],
    gapPercent: 10,
    enc: 3.4,
    costSp: 520,
    laterality: "shared",
  },
  {
    id: "scale-hauberk",
    name: "Scale Hauberk",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Th",
    cover: [
      "Th",
      "Ab",
      "Gr",
      "RSh",
      "LSh",
      "RUA",
      "LUA",
      "REl",
      "LEl",
      "RFo",
      "LFo",
    ],
    gapPercent: 15,
    enc: 4.6,
    costSp: 750,
    laterality: "shared",
  },
  {
    id: "scale-sleeves-right",
    name: "Scale Sleeves (Right)",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Ua",
    cover: ["RUA", "REl", "RFo"],
    gapPercent: 20,
    enc: 0.6,
    costSp: 90,
    laterality: "right",
  },
  {
    id: "scale-sleeves-left",
    name: "Scale Sleeves (Left)",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Ua",
    cover: ["LUA", "LEl", "LFo"],
    gapPercent: 20,
    enc: 0.6,
    costSp: 90,
    laterality: "left",
  },
  {
    id: "scale-hand-guards-right",
    name: "Scale Hand Guards (Right)",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Ha",
    cover: ["RHa"],
    gapPercent: 50,
    enc: 0.3,
    costSp: 55,
    laterality: "right",
  },
  {
    id: "scale-hand-guards-left",
    name: "Scale Hand Guards (Left)",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Ha",
    cover: ["LHa"],
    gapPercent: 50,
    enc: 0.3,
    costSp: 55,
    laterality: "left",
  },
  {
    id: "scale-skirt",
    name: "Scale Skirt",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Hp",
    cover: ["Hp", "Gr", "RTg", "LTg"],
    gapPercent: 15,
    enc: 1.4,
    costSp: 200,
    laterality: "shared",
  },
  {
    id: "scale-leggings",
    name: "Scale Leggings",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Tg",
    cover: ["RTg", "LTg", "RKn", "LKn", "RCf", "LCf"],
    gapPercent: 20,
    enc: 2.2,
    costSp: 360,
    laterality: "shared",
  },
  {
    id: "scale-chausses",
    name: "Scale Chausses",
    build: "Scale",
    garmentSlots: ["Flexible", "Rigid"],
    mount: "Tg",
    cover: ["RTg", "LTg", "RKn", "LKn", "RCf", "LCf", "RFt", "LFt"],
    gapPercent: 20,
    enc: 3.2,
    costSp: 520,
    laterality: "shared",
  },

  // --- Lamellar (Rigid) ---
  {
    id: "lamellar-collar",
    name: "Lamellar Collar",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Nk",
    cover: ["Nk"],
    gapPercent: 5,
    enc: 0.4,
    costSp: 60,
    laterality: "shared",
  },
  {
    // Doesn't cover Fa -- see file header note on Face coverage.
    id: "lamellar-coif",
    name: "Lamellar Coif",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Sk",
    cover: ["Sk", "Nk"],
    gapPercent: 10,
    enc: 0.8,
    costSp: 120,
    laterality: "shared",
  },
  {
    id: "lamellar-mantlet",
    name: "Lamellar Mantlet",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Nk",
    cover: ["Nk", "RSh", "LSh", "Th"],
    gapPercent: 5,
    enc: 1.0,
    costSp: 150,
    laterality: "shared",
  },
  {
    id: "lamellar-vest",
    name: "Lamellar Vest",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Th",
    cover: ["Th", "Ab"],
    gapPercent: 15,
    enc: 2.2,
    costSp: 320,
    laterality: "shared",
  },
  {
    id: "lamellar-cuirass",
    name: "Lamellar Cuirass",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Th",
    cover: ["Th", "Ab", "RSh", "LSh", "RUA", "LUA"],
    gapPercent: 15,
    enc: 3.2,
    costSp: 560,
    laterality: "shared",
  },
  {
    id: "lamellar-coat",
    name: "Lamellar Coat",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Th",
    cover: [
      "Th",
      "Ab",
      "Gr",
      "Hp",
      "RTg",
      "LTg",
      "RSh",
      "LSh",
      "RUA",
      "LUA",
      "REl",
      "LEl",
      "RFo",
      "LFo",
    ],
    gapPercent: 10,
    enc: 4.4,
    costSp: 820,
    laterality: "shared",
  },
  {
    id: "lamellar-sleeves-right",
    name: "Lamellar Sleeves (Right)",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Ua",
    cover: ["RUA", "REl", "RFo"],
    gapPercent: 15,
    enc: 0.55,
    costSp: 90,
    laterality: "right",
  },
  {
    id: "lamellar-sleeves-left",
    name: "Lamellar Sleeves (Left)",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Ua",
    cover: ["LUA", "LEl", "LFo"],
    gapPercent: 15,
    enc: 0.55,
    costSp: 90,
    laterality: "left",
  },
  {
    id: "lamellar-gauntlets-right",
    name: "Lamellar Gauntlets (Right)",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Ha",
    cover: ["RHa"],
    gapPercent: 20,
    enc: 0.3,
    costSp: 60,
    laterality: "right",
  },
  {
    id: "lamellar-gauntlets-left",
    name: "Lamellar Gauntlets (Left)",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Ha",
    cover: ["LHa"],
    gapPercent: 20,
    enc: 0.3,
    costSp: 60,
    laterality: "left",
  },
  {
    id: "lamellar-skirt",
    name: "Lamellar Skirt",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Hp",
    cover: ["Hp", "Gr", "RTg", "LTg"],
    gapPercent: 10,
    enc: 1.3,
    costSp: 210,
    laterality: "shared",
  },
  {
    id: "lamellar-leggings",
    name: "Lamellar Leggings",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Tg",
    cover: ["RTg", "LTg", "RKn", "LKn", "RCf", "LCf"],
    gapPercent: 15,
    enc: 2.0,
    costSp: 380,
    laterality: "shared",
  },
  {
    id: "lamellar-chausses",
    name: "Lamellar Chausses",
    build: "Lamellar",
    garmentSlots: ["Rigid"],
    mount: "Tg",
    cover: ["RTg", "LTg", "RKn", "LKn", "RCf", "LCf", "RFt", "LFt"],
    gapPercent: 15,
    enc: 3.0,
    costSp: 560,
    laterality: "shared",
  },

  // --- Plate (Rigid) -- every lateral piece here is individually forged ---
  {
    id: "plate-helm",
    name: "Plate Helm",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sk",
    cover: ["Sk", "Fa"],
    gapPercent: 15,
    enc: 1.0,
    costSp: 220,
    laterality: "shared",
  },
  {
    id: "plate-gorget",
    name: "Plate Gorget",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Nk",
    cover: ["Nk"],
    gapPercent: 5,
    enc: 0.3,
    costSp: 80,
    laterality: "shared",
  },
  {
    id: "plate-spaulders-right",
    name: "Plate Spaulders (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sh",
    cover: ["RSh"],
    gapPercent: 25,
    enc: 0.3,
    costSp: 75,
    laterality: "right",
  },
  {
    id: "plate-spaulders-left",
    name: "Plate Spaulders (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sh",
    cover: ["LSh"],
    gapPercent: 25,
    enc: 0.3,
    costSp: 75,
    laterality: "left",
  },
  {
    id: "plate-pauldrons-right",
    name: "Plate Pauldrons (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sh",
    cover: ["RSh", "RUA"],
    gapPercent: 15,
    enc: 0.45,
    costSp: 125,
    laterality: "right",
  },
  {
    id: "plate-pauldrons-left",
    name: "Plate Pauldrons (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sh",
    cover: ["LSh", "LUA"],
    gapPercent: 15,
    enc: 0.45,
    costSp: 125,
    laterality: "left",
  },
  {
    id: "plate-cuirass",
    name: "Plate Cuirass",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Th",
    cover: ["Th", "Ab"],
    gapPercent: 15,
    enc: 2.8,
    costSp: 800,
    laterality: "shared",
  },
  {
    id: "plate-rerebraces-right",
    name: "Plate Rerebraces (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Ua",
    cover: ["RUA"],
    gapPercent: 20,
    enc: 0.35,
    costSp: 90,
    laterality: "right",
  },
  {
    id: "plate-rerebraces-left",
    name: "Plate Rerebraces (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Ua",
    cover: ["LUA"],
    gapPercent: 20,
    enc: 0.35,
    costSp: 90,
    laterality: "left",
  },
  {
    id: "plate-couters-right",
    name: "Plate Couters (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "El",
    cover: ["REl"],
    gapPercent: 30,
    enc: 0.15,
    costSp: 50,
    laterality: "right",
  },
  {
    id: "plate-couters-left",
    name: "Plate Couters (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "El",
    cover: ["LEl"],
    gapPercent: 30,
    enc: 0.15,
    costSp: 50,
    laterality: "left",
  },
  {
    id: "plate-vambraces-right",
    name: "Plate Vambraces (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Fo",
    cover: ["RFo"],
    gapPercent: 10,
    enc: 0.35,
    costSp: 90,
    laterality: "right",
  },
  {
    id: "plate-vambraces-left",
    name: "Plate Vambraces (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Fo",
    cover: ["LFo"],
    gapPercent: 10,
    enc: 0.35,
    costSp: 90,
    laterality: "left",
  },
  {
    id: "plate-gauntlets-right",
    name: "Plate Gauntlets (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Ha",
    cover: ["RHa"],
    gapPercent: 20,
    enc: 0.25,
    costSp: 90,
    laterality: "right",
  },
  {
    id: "plate-gauntlets-left",
    name: "Plate Gauntlets (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Ha",
    cover: ["LHa"],
    gapPercent: 20,
    enc: 0.25,
    costSp: 90,
    laterality: "left",
  },
  {
    id: "plate-fauld",
    name: "Plate Fauld",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Hp",
    cover: ["Hp", "Gr"],
    gapPercent: 15,
    enc: 0.8,
    costSp: 180,
    laterality: "shared",
  },
  {
    id: "plate-tassets-right",
    name: "Plate Tassets (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Tg",
    cover: ["RTg"],
    gapPercent: 20,
    enc: 0.4,
    costSp: 100,
    laterality: "right",
  },
  {
    id: "plate-tassets-left",
    name: "Plate Tassets (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Tg",
    cover: ["LTg"],
    gapPercent: 20,
    enc: 0.4,
    costSp: 100,
    laterality: "left",
  },
  {
    id: "plate-cuisses-right",
    name: "Plate Cuisses (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Tg",
    cover: ["RTg"],
    gapPercent: 25,
    enc: 0.45,
    costSp: 120,
    laterality: "right",
  },
  {
    id: "plate-cuisses-left",
    name: "Plate Cuisses (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Tg",
    cover: ["LTg"],
    gapPercent: 25,
    enc: 0.45,
    costSp: 120,
    laterality: "left",
  },
  {
    id: "plate-poleyns-right",
    name: "Plate Poleyns (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Kn",
    cover: ["RKn"],
    gapPercent: 30,
    enc: 0.15,
    costSp: 50,
    laterality: "right",
  },
  {
    id: "plate-poleyns-left",
    name: "Plate Poleyns (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Kn",
    cover: ["LKn"],
    gapPercent: 30,
    enc: 0.15,
    costSp: 50,
    laterality: "left",
  },
  {
    id: "plate-greaves-right",
    name: "Plate Greaves (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Cf",
    cover: ["RCf"],
    gapPercent: 15,
    enc: 0.4,
    costSp: 110,
    laterality: "right",
  },
  {
    id: "plate-greaves-left",
    name: "Plate Greaves (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Cf",
    cover: ["LCf"],
    gapPercent: 15,
    enc: 0.4,
    costSp: 110,
    laterality: "left",
  },
  {
    id: "plate-sabatons-right",
    name: "Plate Sabatons (Right)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Ft",
    cover: ["RFt"],
    gapPercent: 15,
    enc: 0.3,
    costSp: 90,
    laterality: "right",
  },
  {
    id: "plate-sabatons-left",
    name: "Plate Sabatons (Left)",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Ft",
    cover: ["LFt"],
    gapPercent: 15,
    enc: 0.3,
    costSp: 90,
    laterality: "left",
  },
  {
    id: "kettle-hat",
    name: "Kettle Hat",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sk",
    cover: ["Sk"],
    gapPercent: 40,
    enc: 0.8,
    costSp: 180,
    laterality: "shared",
  },
  {
    id: "kettle-hat-and-bevor",
    name: "Kettle Hat + Bevor",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sk",
    cover: ["Sk", "Fa", "Nk"],
    gapPercent: 20,
    enc: 1.2,
    costSp: 350,
    laterality: "shared",
  },
  {
    id: "sallet",
    name: "Sallet",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sk",
    cover: ["Sk", "Fa", "Nk"],
    gapPercent: 20,
    enc: 1.0,
    costSp: 350,
    laterality: "shared",
  },
  {
    id: "barbute",
    name: "Barbute",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sk",
    cover: ["Sk", "Fa"],
    gapPercent: 30,
    enc: 1.1,
    costSp: 300,
    laterality: "shared",
  },
  {
    id: "bevor",
    name: "Bevor",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Fa",
    cover: ["Fa", "Nk"],
    gapPercent: 25,
    enc: 0.4,
    costSp: 120,
    laterality: "shared",
  },
  {
    id: "armet",
    name: "Armet",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sk",
    cover: ["Sk", "Fa", "Nk"],
    gapPercent: 5,
    enc: 1.1,
    costSp: 800,
    laterality: "shared",
  },
  {
    id: "close-helm",
    name: "Close Helm",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sk",
    cover: ["Sk", "Fa", "Nk"],
    gapPercent: 5,
    enc: 1.2,
    costSp: 900,
    laterality: "shared",
  },
  {
    id: "great-helm",
    name: "Great Helm",
    build: "Plate",
    garmentSlots: ["Rigid"],
    mount: "Sk",
    cover: ["Sk", "Fa", "Nk"],
    gapPercent: 15,
    enc: 1.5,
    costSp: 700,
    laterality: "shared",
  },

  // --- Articulated Plate (Rigid) -- explicitly all shared, complete suits ---
  {
    id: "upper-harness",
    name: "Upper Harness",
    build: "ArticulatedPlate",
    garmentSlots: ["Rigid"],
    mount: "Th",
    cover: [
      "Nk",
      "RSh",
      "LSh",
      "RUA",
      "LUA",
      "REl",
      "LEl",
      "RFo",
      "LFo",
      "RHa",
      "LHa",
      "Th",
      "Ab",
    ],
    gapPercent: 5,
    enc: 4.5,
    costSp: 3500,
    laterality: "shared",
  },
  {
    id: "lower-harness",
    name: "Lower Harness",
    build: "ArticulatedPlate",
    garmentSlots: ["Rigid"],
    mount: "Hp",
    cover: ["Hp", "Gr", "RTg", "LTg", "RKn", "LKn", "RCf", "LCf", "RFt", "LFt"],
    gapPercent: 5,
    enc: 3.5,
    costSp: 2500,
    laterality: "shared",
  },
  {
    id: "full-harness",
    name: "Full Harness",
    build: "ArticulatedPlate",
    garmentSlots: ["Rigid"],
    mount: "Th",
    cover: [
      "Nk",
      "RSh",
      "LSh",
      "RUA",
      "LUA",
      "REl",
      "LEl",
      "RFo",
      "LFo",
      "RHa",
      "LHa",
      "Th",
      "Ab",
      "Gr",
      "Hp",
      "RTg",
      "LTg",
      "RKn",
      "LKn",
      "RCf",
      "LCf",
      "RFt",
      "LFt",
    ],
    gapPercent: 5,
    enc: 8.0,
    costSp: 6000,
    laterality: "shared",
  },
  {
    // The doc lists Armet/Close Helm/Great Helm a second time here (as
    // "Separate Helmet Options", with a Cover of "Sk Fa" rather than the
    // Plate section's "Sk Fa Nk") -- not re-added to avoid duplicate near-
    // identical catalog entries. Articulated Helm is unique to this table.
    id: "articulated-helm",
    name: "Articulated Helm",
    build: "ArticulatedPlate",
    garmentSlots: ["Rigid"],
    mount: "Sk",
    cover: ["Sk", "Fa"],
    gapPercent: 10,
    enc: 1.0,
    costSp: 600,
    laterality: "shared",
  },
];
